### ISSUE TITLE
RDK does not update ruby version when .ruby_version is updated

### ISSUE THREAD

**Issue by wubrg** [builtbyrobots/rdk#2]
When attempting to switch ruby versions after rdk has been activated I noticed that it wasn't actually updating the ruby path to use the new ruby version. 

Steps to reproduce: 
- cd into project and activate `rdk`
- verify ruby version in `.ruby_version` and version reported by `ruby?` are the same
- verify that ruby path in `.rdk` matches the ruby version above
- verify that `which ruby` matches the ruby version
- switch ruby version in `.ruby_version` to a different ruby version
- cd out and back into project directory
- verify that rdk reports the updated ruby version
- verify that `ruby?` reports the updated ruby version
- verify that `which ruby` reports the old ruby version
- verify that `.rdk` contains the old ruby version

**Comment by jpruetting** [comment]
Fixed on master branch
